### ISSUE TITLE
无效的CHATGPT_LANGUAGE配置

### ISSUE THREAD

**Issue by lizhijundev** [whatwewant/chatgpt-for-chatbot-feishu#53]
https://github.com/go-zoox/chatgpt-for-chatbot-feishu/blob/73558ce58c1e89be40de2484dded587d30825dfd/main.go#L129

CHATGPT_LANGUAGE环境变量中定义，在main.go中未使用

**Comment by whatwewant** [comment]
确实，是个 BUG，修
