### ISSUE TITLE
也支持命令（/chatgpt）触发，格式：/chatgpt 你的问题，这个怎么用？

### ISSUE THREAD

**Issue by talang-zz** [whatwewant/chatgpt-for-chatbot-feishu#57]
提示：{"code":405,"message":"Method not allowed","method":"GET","path":"/chatgpt","timestamp":"2023-03-21T10:35:14.593113636+08:00"}

**Comment by whatwewant** [comment]
这个不是接口，是在群里通过 `/chatgpt <你的 prompt>` 替代 at 机器人，类似 tg 的机器人命令

**Comment by whatwewant** [comment]
方便一些
