### ISSUE TITLE
超时时间配置

### ISSUE THREAD

**Issue by SuperLight-007** [whatwewant/chatgpt-for-chatbot-feishu#59]
能支持下http的超时时间配置不，有时候到等比较久gpt的回答。

**Comment by SuperLight-007** [comment]
看了代码发现用的是go底层标准库，也没有限制客户端超时时间。但是系统上的tcp fin时间我也从默认60调整成300了。但是就是不生效。依然是一分钟客户端自己报超时。

**Comment by SuperLight-007** [comment]
在openai包的底层fetch包这里
![image](https://user-images.githubusercontent.com/39428543/230597067-e08539c6-31fa-4208-97a2-05041e18c389.png)

**Comment by whatwewant** [comment]
@SuperLight-007 非常感谢，这个问题之前没太注意，确实是个问题
