### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by xinmengliaowuhen** [whatwewant/chatgpt-for-chatbot-feishu#71]
failed to request answer: failed to ask: ErrSendingRequest(3):  error sending request, err: Post "https://api.openai.com/v1/chat/completions": dial tcp 31.13.84.2:443: connect: connection refused(Please check your network, maybe use bad proxy or network offline)

**Comment by whatwewant** [comment]
不要在国内或者本地部署，需要部署到国外服务器
