### ISSUE TITLE
现在不回复消息了吗？

### ISSUE THREAD

**Issue by moonfdd** [whatwewant/chatgpt-for-chatbot-feishu#72]
![image](https://user-images.githubusercontent.com/66774304/237000368-27567b6e-3e2d-4353-9ffa-1f5e407eb0a5.png)

**Comment by moonfdd** [comment]
![image](https://user-images.githubusercontent.com/66774304/237000515-fd072855-5bab-4b31-833a-07e95fe04535.png)

**Comment by whatwewant** [comment]
网络问题

**Comment by moonfdd** [comment]
现在可以了，谢谢了
