### ISSUE TITLE
提示gpt-4的模型不存在

### ISSUE THREAD

**Issue by lanco531** [whatwewant/chatgpt-for-chatbot-feishu#73]
我设置了gpt-4的模型，并且使用的是ChatGPT Plus订阅会员的Key，
![image](https://github.com/whatwewant/chatgpt-for-chatbot-feishu/assets/6062815/bb1089e1-29d6-4f0a-97d9-cc747acabc25)

运行后报错：
![image](https://github.com/whatwewant/chatgpt-for-chatbot-feishu/assets/6062815/a61c11d7-97b1-450a-9eab-ed4e4ed52e91)

**Comment by whatwewant** [comment]
看起来你的 API Key 对应的账户没有申请到 GPT-4

waitlist: https://openai.com/waitlist/gpt-4-api
