### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by SakaiIzumii** [whatwewant/chatgpt-for-chatbot-feishu#84]
报错如下

ERROR failed to get bot info: refresh access token failed(1): ErrSendingRequest(3):  error sending request, err: Post "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal": dial tcp: lookup open.feishu.cn on 127.0.0.11:53: server misbehaving(Please check your network, maybe use bad proxy or network offline)

proxy指向了本地代理,

**Comment by whatwewant** [comment]
看起来你的 Docker 服务的 DNS 有问题，无法解析飞书域名，重启下 Docker Daemon，不是代理问题
